FROM node:18-alpine as build-stage
WORKDIR /app
COPY package*.json ./

# 이전 cache 삭제
# RUN npm cache verify 

# RUN npm cache clean --force

RUN npm install

COPY ./ .

RUN npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf