[[redirects]]
  from = "/api/*"
  to = "https://api.kimjuchan97.xyz/:splat"
  status = 200
  
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

